### ISSUE TITLE
刘海屏的判断要更新一下

### ISSUE THREAD

**Issue by MakeForce** [yfming93/FMMacroKit#1]
https://github.com/yfming93/FMMacroKit/blob/4c21cd75cb50362ad4d3068094c7701c56f9f70c/FMMacroKit/FMMacroKitTools.m#L87

iPhone12,8 不是刘海屏

https://github.com/react-native-community/react-native-device-info/blob/0808195a3b905ead1350fadb50fbf1b67a26f69f/ios/RNDeviceInfo/RNDeviceInfo.m#L219
https://github.com/react-native-community/react-native-device-info/blob/0808195a3b905ead1350fadb50fbf1b67a26f69f/src/internal/devicesWithNotch.ts#L3

**Comment by yfming93** [comment]
Fixed it
